services:
  web:
    container_name: cse-apache
    build:
      context: "."
      args:
      - TARGET_USER=cs3231
      - TARGET_GROUP=cs3231
      - HOST_UID=1000
      - HOST_GID=1000
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/conf:/etc/apache2"
      - "${PWD}/logs:/var/log/apache2"
      - "${PWD}/home:/home"
      - "/proc/sys/fs/binfmt_misc:/binfmt_misc:ro"

