#!/bin/sh
set -e
#set -x

# Apache gets grumpy about PID files pre-existing
#rm -f /usr/local/apache2/logs/httpd.pid


# Load the following envvars from the debian defaults
. /etc/apache2/envvars
#Mutex file:${APACHE_LOCK_DIR} default
#APACHE_RUN_DIR=
#APACHE_PID_FILE=
#APACHE_RUN_USER=www-data
#APACHE_RUN_GROUP=www-data
#APACHE_LOG_DIR=/var/log/apache2

# A sanity check that PHP has been registered the kernel
if [ ! -f /binfmt_misc/PHP ]; then
    echo 'PHP might not be registered with binfmt_misc.'
    echo 'You may need to run the following as root.'
    echo "echo ':PHP:E::php::/usr/bin/php-cgi:'  > /proc/sys/fs/binfmt_misc/register"
    exit 1
fi

exec /usr/sbin/apache2 -DFOREGROUND "$@"
